# Hybrid network for classification

In [2]:
pip install lazypredict

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
# Imports
import tensorflow as tf
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from lazypredict.supervised import LazyRegressor
import numpy as np
import lazypredict

#from sklearn.metrics import accuracy_score, balanced_accuracy_score, roc_auc_score, f1_score

/Users/manwest/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
df = pd.read_csv('/Users/manwest/Git/HNN-Synthetic-Data/Datasets/DIS_lab_LoS_8.csv')
df

Antenna1Subcarrier1Module  Antenna1Subcarrier1Angle  \
0                            0.28                      3.14   
1                            0.31                      2.97   
2                            0.32                      2.75   
3                            0.34                      2.54   
4                            0.35                      2.49   
...                           ...                       ...   
251999                       0.39                      0.01   
252000                       0.33                     -0.25   
252001                       0.33                     -0.45   
252002                       0.32                     -0.80   
252003                       0.31                     -1.12   

        Antenna1Subcarrier2Module  Antenna1Subcarrier2Angle  \
0                            0.27                      3.02   
1                            0.31                      2.83   
2                            0.32                      2.71   
3                            0.33                      2.55   
4                            0.34                      2.47   
...                           ...                       ...   
251999                       0.40                      0.00   
252000                       0.37                     -0.21   
252001                       0.35                     -0.49   
252002                       0.33                     -0.86   
252003                       0.32                     -1.11   

        Antenna1Subcarrier3Module  Antenna1Subcarrier3Angle  \
0                            0.27                      3.05   
1                            0.30                      2.91   
2                            0.33                      2.72   
3                            0.36                      2.55   
4                            0.36                      2.40   
...                           ...                       ...   
251999                       0.41                     -0.06   
252000                       0.39                     -0.28   
252001                       0.36                     -0.59   
252002                       0.33                     -0.86   
252003                       0.31                     -1.17   

        Antenna1Subcarrier4Module  Antenna1Subcarrier4Angle  \
0                            0.28                      3.00   
1                            0.34                      2.78   
2                            0.35                      2.67   
3                            0.37                      2.47   
4                            0.37                      2.38   
...                           ...                       ...   
251999                       0.42                     -0.17   
252000                       0.39                     -0.39   
252001                       0.37                     -0.66   
252002                       0.33                     -0.98   
252003                       0.35                     -1.27   

        Antenna1Subcarrier5Module  Antenna1Subcarrier5Angle  ...  \
0                            0.28                      2.99  ...   
1                            0.31                      2.74  ...   
2                            0.33                      2.63  ...   
3                            0.35                      2.44  ...   
4                            0.37                      2.32  ...   
...                           ...                       ...  ...   
251999                       0.41                     -0.20  ...   
252000                       0.41                     -0.41  ...   
252001                       0.38                     -0.66  ...   
252002                       0.35                     -0.97  ...   
252003                       0.37                     -1.27  ...   

        Antenna8Subcarrier97Module  Antenna8Subcarrier97Angle  \
0                             0.27                       0.69   
1                             0.2

In [3]:

#df_x = df.iloc[:,:-2]
#df_x
df.iloc[:,:-2]

Antenna1Subcarrier1Module  Antenna1Subcarrier1Angle  \
0                            0.28                      3.14   
1                            0.31                      2.97   
2                            0.32                      2.75   
3                            0.34                      2.54   
4                            0.35                      2.49   
...                           ...                       ...   
251999                       0.39                      0.01   
252000                       0.33                     -0.25   
252001                       0.33                     -0.45   
252002                       0.32                     -0.80   
252003                       0.31                     -1.12   

        Antenna1Subcarrier2Module  Antenna1Subcarrier2Angle  \
0                            0.27                      3.02   
1                            0.31                      2.83   
2                            0.32                      2.71   
3                            0.33                      2.55   
4                            0.34                      2.47   
...                           ...                       ...   
251999                       0.40                      0.00   
252000                       0.37                     -0.21   
252001                       0.35                     -0.49   
252002                       0.33                     -0.86   
252003                       0.32                     -1.11   

        Antenna1Subcarrier3Module  Antenna1Subcarrier3Angle  \
0                            0.27                      3.05   
1                            0.30                      2.91   
2                            0.33                      2.72   
3                            0.36                      2.55   
4                            0.36                      2.40   
...                           ...                       ...   
251999                       0.41                     -0.06   
252000                       0.39                     -0.28   
252001                       0.36                     -0.59   
252002                       0.33                     -0.86   
252003                       0.31                     -1.17   

        Antenna1Subcarrier4Module  Antenna1Subcarrier4Angle  \
0                            0.28                      3.00   
1                            0.34                      2.78   
2                            0.35                      2.67   
3                            0.37                      2.47   
4                            0.37                      2.38   
...                           ...                       ...   
251999                       0.42                     -0.17   
252000                       0.39                     -0.39   
252001                       0.37                     -0.66   
252002                       0.33                     -0.98   
252003                       0.35                     -1.27   

        Antenna1Subcarrier5Module  Antenna1Subcarrier5Angle  ...  \
0                            0.28                      2.99  ...   
1                            0.31                      2.74  ...   
2                            0.33                      2.63  ...   
3                            0.35                      2.44  ...   
4                            0.37                      2.32  ...   
...                           ...                       ...  ...   
251999                       0.41                     -0.20  ...   
252000                       0.41                     -0.41  ...   
252001                       0.38                     -0.66  ...   
252002                       0.35                     -0.97  ...   
252003                       0.37                     -1.27  ...   

        Antenna8Subcarrier96Module  Antenna8Subcarrier96Angle  \
0                             0.27                       0.56   
1                             0.3

In [4]:
X = df.iloc[:,:-2].values
y = df['PositionX'].values
y

array([-1437, -1437, -1437, ...,  1357,  1357,  1357])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=64, shuffle=True)
X_train

array([[ 1.00249932,  1.34282925,  1.03939286, ..., -2.4539214 ,
         0.5851818 , -2.48874602],
       [ 0.58288266,  2.0974236 ,  0.57825695, ...,  2.38588873,
         0.82930341,  2.39617318],
       [ 0.42821124, -0.94736552,  0.43478861, ...,  0.15112319,
         0.76511662,  0.13828696],
       ...,
       [ 0.70291881,  0.33405222,  0.75244758, ...,  2.95337115,
         0.15799803,  2.99270271],
       [ 0.79580197,  0.8131688 ,  0.8203962 , ..., -1.72082328,
         0.3661888 , -1.76400781],
       [ 0.64820214,  0.26836621,  0.69870573, ..., -1.68488211,
         0.3334986 , -1.66463754]])

In [6]:
y_test

array([  357,  -862, -1287, ...,  1347,   467,  -437])

In [7]:
del df
#del df_x
#del df_y

In [8]:
#import lazypredict
lazypredict.supervised.REGRESSORS

[('AdaBoostRegressor', sklearn.ensemble._weight_boosting.AdaBoostRegressor),
 ('BaggingRegressor', sklearn.ensemble._bagging.BaggingRegressor),
 ('BayesianRidge', sklearn.linear_model._bayes.BayesianRidge),
 ('DecisionTreeRegressor', sklearn.tree._classes.DecisionTreeRegressor),
 ('DummyRegressor', sklearn.dummy.DummyRegressor),
 ('ElasticNet', sklearn.linear_model._coordinate_descent.ElasticNet),
 ('ElasticNetCV', sklearn.linear_model._coordinate_descent.ElasticNetCV),
 ('ExtraTreeRegressor', sklearn.tree._classes.ExtraTreeRegressor),
 ('ExtraTreesRegressor', sklearn.ensemble._forest.ExtraTreesRegressor),
 ('GammaRegressor', sklearn.linear_model._glm.glm.GammaRegressor),
 ('GaussianProcessRegressor',
  sklearn.gaussian_process._gpr.GaussianProcessRegressor),
 ('GradientBoostingRegressor', sklearn.ensemble._gb.GradientBoostingRegressor),
 ('HistGradientBoostingRegressor',
  sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingRegressor),
 ('HuberRegressor', sk

In [9]:
#lazypredict.supervised.REGRESSORS = lazypredict.supervised.REGRESSORS[33:36]
#lazypredict.supervised.REGRESSORS

[('RandomForestRegressor', sklearn.ensemble._forest.RandomForestRegressor),
 ('Ridge', sklearn.linear_model._ridge.Ridge),
 ('RidgeCV', sklearn.linear_model._ridge.RidgeCV)]

In [9]:
lazypredict.supervised.REGRESSORS = lazypredict.supervised.REGRESSORS[36:42]
lazypredict.supervised.REGRESSORS

[('SGDRegressor', sklearn.linear_model._stochastic_gradient.SGDRegressor),
 ('SVR', sklearn.svm._classes.SVR),
 ('TransformedTargetRegressor',
  sklearn.compose._target.TransformedTargetRegressor),
 ('TweedieRegressor', sklearn.linear_model._glm.glm.TweedieRegressor),
 ('XGBRegressor', xgboost.sklearn.XGBRegressor),
 ('LGBMRegressor', lightgbm.sklearn.LGBMRegressor)]

In [11]:
#regressor=['RandomForestRegressor', 'XGBRegressor', 'GradientBoostingRegressor', 'HistGradientBoostingRegressor']
reg = LazyRegressor(verbose=2, ignore_warnings=True, custom_metric=None)

In [12]:
models, predictions = reg.fit(X_train, X_test, y_train, y_test)

 17%|█▋        | 1/6 [06:47<33:56, 407.30s/it]

{'Model': 'SGDRegressor', 'R-Squared': 0.7836456753074956, 'Adjusted R-Squared': 0.7794014051353789, 'RMSE': 396.72193252221695, 'Time taken': 407.2990620136261}


 33%|███▎      | 2/6 [7:52:53<18:27:54, 16618.65s/it]

{'Model': 'SVR', 'R-Squared': 0.708490853175055, 'Adjusted R-Squared': 0.7027722543972088, 'RMSE': 460.4998718458201, 'Time taken': 27966.595288991928}


 50%|█████     | 3/6 [7:53:13<7:31:58, 9039.36s/it]  

{'Model': 'TransformedTargetRegressor', 'R-Squared': 0.7962177920836576, 'Adjusted R-Squared': 0.7922201518798083, 'RMSE': 385.0228923470329, 'Time taken': 20.00335693359375}


 67%|██████▋   | 4/6 [7:53:26<3:02:31, 5475.69s/it]

{'Model': 'TweedieRegressor', 'R-Squared': 0.6852049315852027, 'Adjusted R-Squared': 0.6790295277835858, 'RMSE': 478.5390471677474, 'Time taken': 12.582077026367188}


 83%|████████▎ | 5/6 [7:53:56<58:31, 3511.95s/it]  

{'Model': 'XGBRegressor', 'R-Squared': 0.9146698621646142, 'Adjusted R-Squared': 0.9129959221622035, 'RMSE': 249.1464159340088, 'Time taken': 30.03504991531372}
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.707179 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 408000
[LightGBM] [Info] Number of data points in the train set: 168842, number of used features: 1600
[LightGBM] [Info] Start training from score -39.394440


100%|██████████| 6/6 [7:54:19<00:00, 4743.31s/it]

{'Model': 'LGBMRegressor', 'R-Squared': 0.8679144804257207, 'Adjusted R-Squared': 0.8653233298596554, 'RMSE': 309.9781092614578, 'Time taken': 23.31557607650757}


In [ ]:
print(models)
